name: CI
on: [push]
env:
  CI: 'true'
jobs:
  tests:
    strategy:
      matrix:
        java: [11,14]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    name: ci tests java-${{ matrix.java }}
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
    - uses: actions/cache@v1
      with:
        path: ~/.n*
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-
    - uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradlew') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - run: sudo apt-get install -y httpie
    - run: npm i -g wait-port
    - run: cd $GITHUB_WORKSPACE && ./gradlew
    - run: java -jar $GITHUB_WORKSPACE/build/libs/*jar &
    - run: wait-port 8080
    - run: http get :8080/api/hello
    - run: http get :8080
